### ISSUE TITLE
Think of app name

### ISSUE THREAD

**Issue by Jay2645** [Jay2645/Crime-Reports-App#4]

**Comment by Jay2645** [comment]
@bryanlorentz: "Crime Time"

**Comment by dvuong2** [comment]
Crime Alert

**Comment by bryanlorentz** [comment]
Crime Watch
Crime Time
Crime Finder
Safe Zone
Crime Zone
Neighborhood Watch

**Comment by Audiocrow** [comment]
I like Safe Zone

**Comment by bryanlorentz** [comment]
WatchDogs

**Comment by Jay2645** [comment]
Neighborhood Watchdogs
Criminos -- The Dominos of Crime
CLOAKMAN

**Comment by Jay2645** [comment]
Crimebusters
*WHO ARE YOU GONNA CALL* (probably 911 your life isn't worth it)

**Comment by dvuong2** [comment]
Crime Dawgzzz
